name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Linux packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libtool-bin libogg-dev doxygen libxml2-utils w3c-sgml-lib libflac-dev
    - name: Setup emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        update: true
    - run: emcc -v
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.26.1
        run_install: true
    - name: Build
      run: ./build.sh
